import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  params: { lang },
  children,
}: {
  params: { lang: string };
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang={lang}>
      <body>{children}</body>
    </html>
  );
}
