// Ported from kalkulacka-2026/apps/web/lib/ai-prompt.ts, adapted to this package's `CandidateMatchViewModel`
// (`match` is the percentage, `candidate.displayName` the name) and to strings handed in rather than read from a
// catalog — the package holds its strings in next-intl messages, which only a component can read.
import type { CandidateViewModel } from "@/view-models/candidate";

import type { QuestionConsensus, TopicMatch } from "./insights";

/** One row of the ranking, as far as the summary needs it. */
export type AiPromptMatch = {
  candidate: Pick<CandidateViewModel, "displayName">;
  /** 0–100, or `undefined` for a candidate who never answered. */
  match?: number;
};

export type AiPromptInput = {
  electionName: string;
  districtName: string;
  answered: number;
  total: number;
  matches: readonly AiPromptMatch[];
  topics: readonly TopicMatch[];
  important: readonly QuestionConsensus[];
  againstTheGrain: readonly QuestionConsensus[];
};

/**
 * The summary's sentences. The parametrised ones are functions rather than
 * templates so the component can hand over `t("promptIntro", values)` as it
 * is, and the catalog stays free to use whatever ICU syntax it likes.
 */
export type AiPromptLabels = {
  /** "Rozhoduji se ve volbách {election} ({district}). Ve volební kalkulačce mám zodpovězeno {answered} ze {total} otázek." */
  intro: (values: { election: string; district: string; answered: number; total: number }) => string;
  /** "Nejvíc se shoduji s těmito stranami:" */
  matches: string;
  /** "Podle jednotlivých témat mi je nejblíž:" */
  topics: string;
  /** "Jako důležité mám označené tyto otázky:" */
  important: string;
  /** "U těchto otázek se se mnou shodlo nejmíň stran:" */
  grain: string;
  /** The question to end on — "Vysvětli mi hlavní rozdíly…". */
  ask: string;
  /** "souhlasím" */
  agree: string;
  /** "nesouhlasím" */
  disagree: string;
  /** "nevím" */
  neutral: string;
  /** "Souhlasí {agreeing} z {responded} stran" — the dashboard's own count, lowercased into a parenthesis here. */
  agreeCount: (values: { agreeing: number; responded: number }) => string;
  /** "74 %", the way the active locale writes it. */
  percent: (value: number) => string;
  /** The locale the sentences are in, for the one case-folding the summary does. */
  locale?: string;
};

/** How many parties the summary names before it stops being a summary. */
const TOP_MATCHES = 3;

function positionOf(answer: boolean | null, labels: AiPromptLabels): string {
  if (answer === true) return labels.agree;
  if (answer === false) return labels.disagree;
  return labels.neutral;
}

/**
 * The copyable summary, assembled here in the browser from the same numbers the
 * screen is showing.
 *
 * No model is involved in writing it and nothing is sent anywhere — it is a
 * template over data the page already has. That matters enough to say out loud
 * on the card itself (`promptNote`), because a block of text captioned "for your
 * AI assistant" is otherwise a reasonable thing to assume was generated by one.
 *
 * Every sentence is phrased to avoid Czech's gendered past tense ("mám
 * zodpovězeno", not "odpověděl jsem"), so the summary reads correctly for
 * whoever copies it without the app ever having to ask.
 */
export function buildAiPrompt({ electionName, districtName, answered, total, matches, topics, important, againstTheGrain }: AiPromptInput, labels: AiPromptLabels): string {
  const sections: string[] = [];

  sections.push(labels.intro({ election: electionName, district: districtName, answered, total }));

  const ranked = matches.filter((entry): entry is AiPromptMatch & { match: number } => entry.match !== undefined).slice(0, TOP_MATCHES);

  if (ranked.length > 0) {
    sections.push([labels.matches, ...ranked.map((entry, index) => `${index + 1}. ${entry.candidate.displayName ?? ""} — ${labels.percent(entry.match)}`)].join("\n"));
  }

  if (topics.length > 0) {
    sections.push([labels.topics, ...topics.map((topic) => `- ${topic.topic}: ${topic.best.candidate.displayName ?? ""} (${labels.percent(topic.best.matchPercentage)})`)].join("\n"));
  }

  if (important.length > 0) {
    sections.push([labels.important, ...important.map((entry) => `- ${entry.question.statement} — ${positionOf(entry.userAnswer, labels)}`)].join("\n"));
  }

  if (againstTheGrain.length > 0) {
    sections.push(
      [
        labels.grain,
        ...againstTheGrain.map(
          (entry) =>
            `- ${entry.question.statement} — ${positionOf(entry.userAnswer, labels)} (${labels.agreeCount({ agreeing: entry.agreeing.length, responded: entry.respondedCount }).toLocaleLowerCase(labels.locale)})`,
        ),
      ].join("\n"),
    );
  }

  sections.push(labels.ask);

  return sections.join("\n\n");
}
